### ISSUE TITLE
Need to set up player party system

### ISSUE THREAD

**Issue by LoneWolfHT** [LoneWolfHT/voxel_knights#5]
- [x] Set up on_joinplayer() code
- [x] Handle leave/joins properly
- [x] Set up door teleports
- [x] Set up system to wait for full party before entering dungeon

**Comment by ghost** [comment]
Yes this needs to be done :)

**Comment by LoneWolfHT** [comment]
> Yes this needs to be done :)

Taking a temporary break while I work on my other projects for a bit too :P
